name: Configure Azure environment

on: workflow_dispatch

env:
  AZURE_RESOURCE_GROUP: probot-applications


jobs:
  destroy-azure-resources:
    runs-on: ubuntu-latest
    steps:

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes
